package HTML;

import Class.ProdutoTexto;
import Estatistica.CalculadorEstatistica;

import java.io.FileWriter;
import java.util.List;

public class GeradorHTML {

    public void gerar(List<ProdutoTexto> textos, String origem) {
        CalculadorEstatistica calc = new CalculadorEstatistica(textos);

        double mediaComplexity    = calc.mediaComplexity();
        double medianaComplexity  = calc.medianaComplexity();
        double modaComplexity     = calc.modaComplexity();
        double minComplexity      = calc.minComplexity();
        double maxComplexity      = calc.maxComplexity();
        double varianciaComplexity     = calc.varianciaComplexity();
        double desvioPadraoComplexity  = calc.desvioPadraoComplexity();

        double mediaSC   = calc.mediaSemanticCoherence();
        double medianaSC = calc.medianaSemanticCoherence();
        double modaSC    = calc.modaSemanticCoherence();
        double minSC     = calc.minSemanticCoherence();
        double maxSC     = calc.maxSemanticCoherence();
        double varianciaSC     = calc.varianciaSemanticCoherence();
        double desvioPadraoSC  = calc.desvioPadraoSemanticCoherence();

        long countAI = calc.countAI();
        long countHuman = calc.countHuman();
        int total = calc.total();

        StringBuilder sb = new StringBuilder();
        sb.append("<!DOCTYPE html>\n");
        sb.append("<html lang=\"pt-BR\">\n");
        sb.append("<head>\n");
        sb.append("  <meta charset=\"UTF-8\">\n");
        sb.append("  <title>Relatório Estatístico — ProdutoTexto</title>\n");
        sb.append("  <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap\" rel=\"stylesheet\">\n");
        sb.append("  <script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\n");
        sb.append("  <script type=\"text/javascript\">\n");
        sb.append("    google.charts.load('current', {'packages':['corechart']});\n");
        sb.append("    google.charts.setOnLoadCallback(drawChart);\n");
        sb.append("    function drawChart() {\n");
        sb.append("      var data = google.visualization.arrayToDataTable([\n");
        sb.append("        ['Autor', 'Quantidade'],\n");
        sb.append("        ['IA', ").append(countAI).append("],\n");
        sb.append("        ['Humanos', ").append(countHuman).append("]\n");
        sb.append("      ]);\n");
        sb.append("      var options = {\n");
        sb.append("        title: 'Distribuição de Textos (IA vs Humanos)',\n");
        sb.append("        pieHole: 0.4,\n");
        sb.append("        colors: ['#6366f1', '#10b981'],\n");
        sb.append("        backgroundColor: 'transparent',\n");
        sb.append("        chartArea: {width:'100%', height:'80%'},\n");
        sb.append("        legend: {position: 'bottom'},\n");
        sb.append("        titleTextStyle: {color: '#1f2937', fontSize: 18}\n");
        sb.append("      };\n");
        sb.append("      var chart = new google.visualization.PieChart(document.getElementById('donutchart'));\n");
        sb.append("      chart.draw(data, options);\n");
        sb.append("    }\n");
        sb.append("  </script>\n");
        sb.append("  <style>\n");
        sb.append("    :root {\n");
        sb.append("      --primary: #6366f1;\n");
        sb.append("      --secondary: #10b981;\n");
        sb.append("      --bg: #f8fafc;\n");
        sb.append("      --card: #ffffff;\n");
        sb.append("      --text: #1f2937;\n");
        sb.append("      --muted: #64748b;\n");
        sb.append("      --border: #e2e8f0;\n");
        sb.append("    }\n");
        sb.append("    body {\n");
        sb.append("      font-family: 'Inter', sans-serif;\n");
        sb.append("      background-color: var(--bg);\n");
        sb.append("      color: var(--text);\n");
        sb.append("      margin: 0;\n");
        sb.append("      padding: 40px 20px;\n");
        sb.append("      display: flex;\n");
        sb.append("      flex-direction: column;\n");
        sb.append("      align-items: center;\n");
        sb.append("    }\n");
        sb.append("    .container {\n");
        sb.append("      max-width: 1000px;\n");
        sb.append("      width: 100%;\n");
        sb.append("      background: var(--card);\n");
        sb.append("      padding: 40px;\n");
        sb.append("      border-radius: 12px;\n");
        sb.append("      box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1);\n");
        sb.append("    }\n");
        sb.append("    h1 {\n");
        sb.append("      font-size: 2.5rem;\n");
        sb.append("      font-weight: 700;\n");
        sb.append("      margin-bottom: 30px;\n");
        sb.append("      text-align: center;\n");
        sb.append("      background: linear-gradient(to right, var(--primary), var(--secondary));\n");
        sb.append("      -webkit-background-clip: text;\n" +
            "      -webkit-text-fill-color: transparent;\n");
        sb.append("    }\n");
        sb.append("    .summary-cards {\n");
        sb.append("      display: grid;\n");
        sb.append("      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));\n");
        sb.append("      gap: 20px;\n");
        sb.append("      margin-bottom: 40px;\n");
        sb.append("    }\n");
        sb.append("    .card {\n");
        sb.append("      padding: 20px;\n");
        sb.append("      border: 1px solid var(--border);\n");
        sb.append("      border-radius: 8px;\n");
        sb.append("      text-align: center;\n");
        sb.append("    }\n");
        sb.append("    .card .value {\n");
        sb.append("      font-size: 1.5rem;\n");
        sb.append("      font-weight: 600;\n");
        sb.append("      display: block;\n");
        sb.append("    }\n");
        sb.append("    .card .label {\n");
        sb.append("      font-size: 0.875rem;\n");
        sb.append("      color: var(--muted);\n");
        sb.append("    }\n");
        sb.append("    .main-content {\n");
        sb.append("      display: flex;\n");
        sb.append("      gap: 40px;\n");
        sb.append("      flex-wrap: wrap;\n");
        sb.append("      justify-content: center;\n");
        sb.append("    }\n");
        sb.append("    #donutchart {\n");
        sb.append("      width: 450px;\n");
        sb.append("      height: 350px;\n");
        sb.append("    }\n");
        sb.append("    table {\n");
        sb.append("      width: 100%;\n");
        sb.append("      border-collapse: collapse;\n");
        sb.append("      margin-top: 20px;\n");
        sb.append("    }\n");
        sb.append("    th, td {\n");
        sb.append("      padding: 12px 15px;\n");
        sb.append("      text-align: left;\n");
        sb.append("      border-bottom: 1px solid var(--border);\n");
        sb.append("    }\n");
        sb.append("    th {\n");
        sb.append("      background-color: #f1f5f9;\n");
        sb.append("      font-weight: 600;\n");
        sb.append("      color: var(--muted);\n");
        sb.append("      text-transform: uppercase;\n");
        sb.append("      font-size: 0.75rem;\n");
        sb.append("      letter-spacing: 0.05em;\n");
        sb.append("    }\n");
        sb.append("    footer {\n");
        sb.append("      margin-top: 40px;\n");
        sb.append("      text-align: center;\n");
        sb.append("      font-size: 0.875rem;\n");
        sb.append("      color: var(--muted);\n");
        sb.append("    }\n");
        sb.append("    a {\n");
        sb.append("      color: var(--primary);\n");
        sb.append("      text-decoration: none;\n");
        sb.append("    }\n");
        sb.append("  </style>\n");
        sb.append("</head>\n");
        sb.append("<body>\n");
        sb.append("  <div class=\"container\">\n");
        sb.append("    <h1>Relatório Estatístico</h1>\n");
        sb.append("    \n");
        sb.append("    <div class=\"summary-cards\">\n");
        sb.append("      <div class=\"card\">\n");
        sb.append("        <span class=\"value\">").append(total).append("</span>\n");
        sb.append("        <span class=\"label\">Total de Registros</span>\n");
        sb.append("      </div>\n");
        sb.append("      <div class=\"card\">\n");
        sb.append("        <span class=\"value\">").append(countAI).append("</span>\n");
        sb.append("        <span class=\"label\">Gerados por IA</span>\n");
        sb.append("      </div>\n");
        sb.append("      <div class=\"card\">\n");
        sb.append("        <span class=\"value\">").append(countHuman).append("</span>\n");
        sb.append("        <span class=\"label\">Escritos por Humanos</span>\n");
        sb.append("      </div>\n");
        sb.append("    </div>\n");
        sb.append("\n");
        sb.append("    <div class=\"main-content\">\n");
        sb.append("      <div id=\"donutchart\"></div>\n");
        sb.append("      \n");
        sb.append("      <table>\n");
        sb.append("        <thead>\n");
        sb.append("          <tr>\n");
        sb.append("            <th>Estatística</th>\n");
        sb.append("            <th>Complexity</th>\n");
        sb.append("            <th>Semantic Coherence</th>\n");
        sb.append("          </tr>\n");
        sb.append("        </thead>\n");
        sb.append("        <tbody>\n");
        sb.append("          <tr>\n");
        sb.append("            <td>Média</td>\n");
        sb.append("            <td>").append(String.format("%.4f", mediaComplexity)).append("</td>\n");
        sb.append("            <td>").append(String.format("%.4f", mediaSC)).append("</td>\n");
        sb.append("          </tr>\n");
        sb.append("          <tr>\n");
        sb.append("            <td>Mediana</td>\n");
        sb.append("            <td>").append(String.format("%.4f", medianaComplexity)).append("</td>\n");
        sb.append("            <td>").append(String.format("%.4f", medianaSC)).append("</td>\n");
        sb.append("          </tr>\n");
        sb.append("          <tr>\n");
        sb.append("            <td>Moda</td>\n");
        sb.append("            <td>").append(String.format("%.2f", modaComplexity)).append("</td>\n");
        sb.append("            <td>").append(String.format("%.2f", modaSC)).append("</td>\n");
        sb.append("          </tr>\n");
        sb.append("          <tr>\n");
        sb.append("            <td>Mínimo</td>\n");
        sb.append("            <td>").append(String.format("%.4f", minComplexity)).append("</td>\n");
        sb.append("            <td>").append(String.format("%.4f", minSC)).append("</td>\n");
        sb.append("          </tr>\n");
        sb.append("          <tr>\n");
        sb.append("            <td>Máximo</td>\n");
        sb.append("            <td>").append(String.format("%.4f", maxComplexity)).append("</td>\n");
        sb.append("            <td>").append(String.format("%.4f", maxSC)).append("</td>\n");
        sb.append("          </tr>\n");
        sb.append("          <tr>\n");
        sb.append("            <td>Variância</td>\n");
        sb.append("            <td>").append(String.format("%.4f", varianciaComplexity)).append("</td>\n");
        sb.append("            <td>").append(String.format("%.4f", varianciaSC)).append("</td>\n");
        sb.append("          </tr>\n");
        sb.append("          <tr>\n");
        sb.append("            <td>Desvio Padrão</td>\n");
        sb.append("            <td>").append(String.format("%.4f", desvioPadraoComplexity)).append("</td>\n");
        sb.append("            <td>").append(String.format("%.4f", desvioPadraoSC)).append("</td>\n");
        sb.append("          </tr>\n");
        sb.append("        </tbody>\n");
        sb.append("      </table>\n");
        sb.append("    </div>\n");
        sb.append("\n");
        sb.append("    <footer>\n");
        sb.append("      <p>Fonte de dados: <strong>").append(origem).append("</strong></p>\n");
        sb.append("      <p>Dataset: <a href=\"https://www.kaggle.com/datasets/algozee/ai-generated-vs-human-written-text-dataset\" target=\"_blank\">AI Generated vs Human Written Text</a></p>\n");
        sb.append("    </footer>\n");
        sb.append("  </div>\n");
        sb.append("</body>\n");
        sb.append("</html>\n");

        try {
            FileWriter fw = new FileWriter("relatorio_estatistico.html");
            fw.write(sb.toString());
            fw.close();
            System.out.println("Relatório HTML gerado com sucesso: relatorio_estatistico.html");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
